name: Release CLI Phar

on:
  push:
    branches:
      - main
    tags:
      - '*'

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build-phar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl
          tools: composer:v2, box

      - name: Set Release Env
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=nightly" >> $GITHUB_ENV
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          fi

      - name: Use local packages
        working-directory: packages/cli
        run: "composer config repositories.local '{\"type\": \"path\", \"url\": \"../*\", \"options\": {\"symlink\": false}}'"

      - name: Install dependencies
        working-directory: packages/cli
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Compile Phar
        working-directory: packages/cli
        run: box compile

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.RELEASER_APP_ID }}
          private-key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: cli,lunapress

      - name: Attest
        uses: actions/attest@v4
        with:
          subject-path: packages/cli/build/lunapress.phar
          github-token: ${{ steps.app-token.outputs.token }}

      - name: Upload Phar
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ github.repository_owner }}/cli
          token: ${{ steps.app-token.outputs.token }}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG == 'nightly' && 'Nightly Build' || env.RELEASE_TAG }}
          prerelease: ${{ env.IS_PRERELEASE }}
          generate_release_notes: true
          append_body: false
#          body: ''
          files: |
            packages/cli/build/lunapress.phar
          make_latest: ${{ env.RELEASE_TAG != 'nightly' }}
