name: Split Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - local_path: 'foundation'
            split_repository: 'foundation'
          - local_path: 'core'
            split_repository: 'core'
          - local_path: 'php-di-adapter'
            split_repository: 'php-di-adapter'
          - local_path: 'frontend'
            split_repository: 'frontend'
          - local_path: 'wp-core'
            split_repository: 'wp-core'
          - local_path: 'wp-assets'
            split_repository: 'wp-assets'
          - local_path: 'frontend-kit'
            split_repository: 'frontend-kit'
          - local_path: 'wp-i18n'
            split_repository: 'wp-i18n'
          - local_path: 'config'
            split_repository: 'config'

    steps:
      - uses: actions/checkout@v6

      - name: Setup GitHub App
        id: setup-app
        uses: ./.github/actions/setup-github-app
        with:
          app_id: ${{ vars.RELEASER_APP_ID }}
          private_key: ${{ secrets.RELEASER_APP_PRIVATE_KEY }}
          repositories: ${{ github.event.repository.name }},foundation,core,php-di-adapter,frontend,wp-core,wp-assets,frontend-kit,wp-i18n,config

      - name: Determine Ref
        id: info
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "type=tag" >> $GITHUB_OUTPUT
            echo "ref=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "type=branch" >> $GITHUB_OUTPUT
            echo "ref=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Split package
        uses: danharrin/monorepo-split-github-action@v2.4.4
        with:
          tag: ${{ steps.info.outputs.type == 'tag' && steps.info.outputs.ref || '' }}
          branch: ${{ steps.info.outputs.type == 'branch' && steps.info.outputs.ref || '' }}
          package_directory: packages/${{ matrix.package.local_path }}
          repository_organization: ${{ github.repository_owner }}
          repository_name: ${{ matrix.package.split_repository }}
          user_name: ${{ steps.setup-app.outputs.bot_name }}
          user_email: ${{ steps.setup-app.outputs.bot_email }}
        env:
          GITHUB_TOKEN: x-access-token:${{ steps.setup-app.outputs.token }}
